apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: krishna
  name: krishna
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krishna
  strategy: {}
  template:
    metadata:
      namespace: dev
      creationTimestamp: null
      labels:
        app: krishna
    spec:
      containers:
      - image: aravindbargurbh/krishna:0.0.1
        name: krishna
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  creationTimestamp: null
  labels:
    app: krishna
  name: krishna-svc
spec:
  ports:
  - name: 9070-9070
    port: 9070
    protocol: TCP
    targetPort: 9070
  selector:
    app: krishna
status:
  loadBalancer: {}
